concurrency: 20         # shoryukenスレッド数
delay: 25               # ポーリングの間隔(秒)
require: ./app/workers  # 使用するworkerを読み込み
pidfile: ./tmp/pids/shoryuken.pid
logfile: ./log/shoryuken.log
queues:
  - sample